- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: ansible
    DURATION: 10 HRS
    Trainer: Sivakumar reddy
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Course Name is:{{COURSE}}, Duration:{{DURATION}}, Trainer:{{Trainer}}"


      