- name: variables from files
  hosts: local
  connection: local
  vars:
  - course.yaml
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duratioin: {{ DURATION }}, Trainer: {{ Trainer }}"
      